name: pusht_value_no_4

obs_dim: 20 # 9*2 keypoints + 2 state
action_dim: 2
keypoint_dim: 2

env_runner:
  _target_: diffusion_policy.env_runner.pusht_keypoints_runner.PushTKeypointsRGRunner
  keypoint_visible_rate: ${keypoint_visible_rate}
  n_train: 6
  n_train_vis: 2
  train_start_seed: 0
  n_test: 50
  n_test_vis: 4
  legacy_test: True
  test_start_seed: 100000
  max_steps: ${n_action_steps}
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  n_latency_steps: ${n_latency_steps}
  fps: 20
  agent_keypoints: False
  past_action: ${past_action_visible}
  n_envs: null

dataset:
  _target_: diffusion_policy.dataset.pusht_dataset.PushTLTLValueDataset
  zarr_path: 'data/pusht/merged_pusht_cchi_v7_replay-seed_42r_33rf.zarr'
  horizon: ${horizon}
  value_name: 'ef_ltls_no_4' 
  filename_ltls: 'data/pusht/LTLs/ltls_no_4.txt'
  filename_values: 'data/pusht/pusht-H16-ef_ltls_no_4-values-merged-seed_42r_33rf.npy'
  num_props: 4
  normalize: False
  ltl_val_ratio: 0.0
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.3
  max_train_episodes: null
